# Generated by Django 2.2 on 2020-06-27 17:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nemotechmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 6, 27, 17, 8, 45, 539837, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nemotechmodel',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('dead', 'Muerto')], default='active', help_text='It maintains the information in case of changes, the one that remains "active" will be the updated one.', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nemotechmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='nemotechmodel',
            name='amount',
            field=models.FloatField(help_text='MONTO', null=True),
        ),
        migrations.AlterField(
            model_name='nemotechmodel',
            name='buy_price',
            field=models.FloatField(help_text='PRECIO_COMRA', null=True),
        ),
        migrations.AlterField(
            model_name='nemotechmodel',
            name='close_price',
            field=models.FloatField(help_text='PRECIO_CIERRE', null=True),
        ),
        migrations.AlterField(
            model_name='nemotechmodel',
            name='coin',
            field=models.CharField(help_text='MONEDA', max_length=10),
        ),
        migrations.AlterField(
            model_name='nemotechmodel',
            name='etfs_foreign',
            field=models.CharField(help_text='ETFs_EXTRANJERO', max_length=1),
        ),
        migrations.AlterField(
            model_name='nemotechmodel',
            name='green_bonus',
            field=models.FloatField(help_text='BONO_VERDE', null=True),
        ),
        migrations.AlterField(
            model_name='nemotechmodel',
            name='sell_price',
            field=models.FloatField(help_text='PRECIO_VENTA', null=True),
        ),
        migrations.AlterField(
            model_name='nemotechmodel',
            name='traded_units',
            field=models.FloatField(help_text='UN_TRANSADAS', null=True),
        ),
        migrations.AlterField(
            model_name='nemotechmodel',
            name='variant',
            field=models.FloatField(help_text='VARIACION', null=True),
        ),
        migrations.AlterField(
            model_name='nemotechmodel',
            name='weight',
            field=models.FloatField(help_text='PESO', null=True),
        ),
    ]
