# Generated by Django 2.2 on 2020-06-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_auto_20200627_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nemotechmodel',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('dead', 'Muerto')], default='active', help_text='It maintains the information in case of changes, the one that remains "active" will be the updated one.', max_length=25),
        ),
    ]
