version: '3'
services:
  db:
    build: ./.docker/db
    ports:
      - 5438:5432
    volumes:
      - ./.docker/db/data:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    ports:
      - 8085:8085
    volumes:
      - .:/app
    tty: true
    depends_on:
      - db
