version: '3'
services:
  db:
    build: ./docker/db
    ports:
      - 5434:5432
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data

  db_test:
    build:
      context: .
      dockerfile: docker/tests/Dockerfile
    ports:
      - 5435:5432

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    command: bash -c "python manage.py migrate; python manage.py runserver 0.0.0.0:8000"
    tty: true
    depends_on:
      - db

  testing:
    depends_on:
      - db_test
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    tty: true
    command: bash -c "pytest -s"
