# Generated by Django 5.0.1 on 2024-01-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetprice',
            old_name='price',
            new_name='adj_close',
        ),
        migrations.AddField(
            model_name='assetprice',
            name='close',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='assetprice',
            name='high',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='assetprice',
            name='low',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='assetprice',
            name='open',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='assetprice',
            name='volume',
            field=models.IntegerField(null=True),
        ),
    ]
