# Generated by Django 5.0.1 on 2024-01-07 03:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=70)),
                ('iso2_code', models.CharField(max_length=2)),
                ('iso3_code', models.CharField(blank=True, max_length=2, null=True)),
                ('languaje', models.CharField(blank=True, max_length=5, null=True)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('currency_symbol', models.CharField(blank=True, max_length=5, null=True)),
                ('currency_decimal_sep', models.CharField(blank=True, max_length=1, null=True)),
                ('currency_thousands_sep', models.CharField(blank=True, max_length=1, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['created_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
    ]
